# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sw7HShsM5Ny4WzRteaPfs_flVQSO_t7i
"""

import csv
import math 
import test
import tkinter

def customer():
  def select_ven():
    def advisior():
      def summory():
        def main():
          print("Please select the options ::- ")
          print("")
          print("1.inform advisior and book van")
          print("")
          print("2.select resion and inform advisior")
          print("")
          print("3.print summory")
          a=int(input())
          if a==1:
            select_van()
            elif a==2:
              advisior()
              elif a==3:
                summory()
                main()

